name: cnn_mamba_k7
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=2.2.6
  - pandas=2.3.3
  - pysam=0.23.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.6.0+cu124
      - causal-conv1d==1.6.1
      - apache-tvm-ffi==0.1.9
      - einops==0.8.2
      - quack-kernels==0.3.10
      - tilelang==0.1.8
      - triton==3.6.0
      - transformers==5.5.4
      - mamba-ssm @ git+https://github.com/state-spaces/mamba.git@be0303b971cd79a4fbbcfc411a01b33f6b0e3602
